### ISSUE TITLE
Not working with Machinomy ^1.6.1

### ISSUE THREAD

**Issue by rhuairahrighairidh** [interledgerjs/ilp-plugin-ethereum#6]
It looks like this plugin is incompatible with machinomy v.1.6.1 despite it as a dependency.

An example:
This function call: https://github.com/interledgerjs/ilp-plugin-ethereum-asym-client/blob/58a71f3c6310188ea668dfd21d431eeb98ba1f69/index.js#L93-L96
Doesn't match what machinomy expects: https://github.com/machinomy/machinomy/blob/b816cb4621bf6e0e51324920a7762dcc262abe49/index.ts#L264-L269

I found a few others incompatibilities well.

**Comment by kincaidoneil** [comment]
Resolved by https://github.com/interledgerjs/ilp-plugin-ethereum-asym-server/commit/4df7490ae8785e68ce22d1a8da0c55135246ebb4.
